name: Docker Image CI

on:
  push:
    tags:
      - '*'

env:
  APP_NAME: 's-pdf'
  DOCKERFILE: './Dockerfile'
  PLATFORMS: 'linux/amd64,linux/arm64'

  GITHUB_CR: 'ghcr.io'
  ALIYUN_CR: 'registry.cn-shanghai.aliyuncs.com'

  DOCKERHUB_REPO: 'nowanti'
  GITHUB_REPO: '${{ github.actor }}'
  ALIYUN_REPO: 'nowanti'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: '${{ env.GITHUB_CR }}'
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: '${{ env.ALIYUN_CR }}'
          username: '${{ secrets.ALIYUN_USERNAME }}'
          password: '${{ secrets.ALIYUN_TOKEN }}'

      - name: Checkout code
        uses: actions/checkout@v4.1.7
      
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: '${{ env.PLATFORMS }}'
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}/${{ env.APP_NAME }}:latest
            ${{ env.DOCKERHUB_REPO }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}
            ${{ env.GITHUB_CR }}/${{ env.GITHUB_REPO }}/${{ env.APP_NAME }}:latest
            ${{ env.GITHUB_CR }}/${{ env.GITHUB_REPO }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}
            ${{ env.ALIYUN_CR }}/${{ env.ALIYUN_REPO }}/${{ env.APP_NAME }}:latest
            ${{ env.ALIYUN_CR }}/${{ env.ALIYUN_REPO }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}